THEMOVIEDB_API_KEY: "05f97be5a9cb29546d1a3222f787becc"
THEMOVIEDB_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNWY5N2JlNWE5Y2IyOTU0NmQxYTMyMjJmNzg3YmVjYyIsInN1YiI6IjY2NDI3YjdkM2Q5MGIyZGY5MzdjOWU1YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.9TO_BaJO1erFgoxY1-iuTXyWBZiUYfnJRiF7j6ne2CM"
THEMOVIEDB_BASE_URL: 'https://api.themoviedb.org/3'


DEV_PASS: 'Fewhuezoo00'

PROD_DB_URL: 'postgresql://postgres.rouzecaoofokcalkogvu:Saxcarbot09!@aws-0-us-east-1.pooler.supabase.com:5432/postgres'
PROD_DB_NAME: 'postgres'
PROD_USER: 'postgres.rouzecaoofokcalkogvu'
PROD_PASS: 'Saxcarbot09!'

SECRET_KEY_BASE: 'ec6690a51f5d4941ddc9848f12205e54454652f663072510476fd2864a5b5de6723d9c8f370cf2bfb9c6f834bc5fa0461f5752959ac744edf84548dbf6578598'